// Code generated by MockGen. DO NOT EDIT.
// Source: osrs-track-search/internal/client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_client.go -package=mocks . Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	client "osrs-track-search/internal/client"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetHighScores mocks base method.
func (m *MockClient) GetHighScores(arg0 string, arg1 client.HighscoresType) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighScores", arg0, arg1)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighScores indicates an expected call of GetHighScores.
func (mr *MockClientMockRecorder) GetHighScores(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighScores", reflect.TypeOf((*MockClient)(nil).GetHighScores), arg0, arg1)
}
